config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :solicitations
  resources :messages
  resources :participantes
  resources :salas
  #get 'salas/:id/solicitacao' => 'salas#show#solicitacao', as: 'solicitacao'
  #post '/sala/:id/solicitacao' => 'salas#show#solicitacao', as: 'solicitacao'
  resources :salas do
  resources :solicitations
  end
  resources :adms
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "salas#index"
  mount ActionCable.server => '/cable'
end

app/models/adm.rb
class Adm < ApplicationRecord
  belongs_to :user
  has_many :salas
  has_many :messages

  accepts_nested_attributes_for :messages, :salas, :user
end

app/controllers/adms_controller.rb
class AdmsController < ApplicationController
  before_action :set_adm, only: [:show, :edit, :update, :destroy]

  # GET /adms
  # GET /adms.json
  def index
    @adms = Adm.all
  end

  # GET /adms/1
  # GET /adms/1.json
  def show
  end

  # GET /adms/new
  def new
    @adm = Adm.new
    #@adm_id = current_user.id
  end

  # GET /adms/1/edit
  def edit
    #@adm_id = current_user.id
  end

  # POST /adms
  # POST /adms.json
  def create
    @adm = Adm.new(adm_params)
    #@adm_id = current_user.id

    respond_to do |format|
      if @adm.save
        format.html { redirect_to @adm, notice: 'Adm was successfully created.' }
        format.json { render :show, status: :created, location: @adm }
      else
        format.html { render :new }
        format.json { render json: @adm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adms/1
  # PATCH/PUT /adms/1.json
  def update
    respond_to do |format|
      if @adm.update(adm_params)
        format.html { redirect_to @adm, notice: 'Adm was successfully updated.' }
        format.json { render :show, status: :ok, location: @adm }
      else
        format.html { render :edit }
        format.json { render json: @adm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adms/1
  # DELETE /adms/1.json
  def destroy
    @adm.destroy
    respond_to do |format|
      format.html { redirect_to adms_url, notice: 'Adm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adm
      @adm = Adm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adm_params
      params.require(:adm).permit(:user_id)
    end
end

app/helpers/adms_helper.rb
module AdmsHelper
end

app/views/adms/_form.html.erb
<%= form_with(model: adm, local: true) do |form| %>
  <% if adm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adm.errors.count, "error") %> prohibited this adm from being saved:</h2>

      <ul>
      <% adm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adms/edit.html.erb
<h1>Editing Adm</h1>

<%= render 'form', adm: @adm %>

<%= link_to 'Show', @adm %> |
<%= link_to 'Back', adms_path %>

app/views/adms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adms.each do |adm| %>
      <tr>
        <td><%= adm.user %></td>
        <td><%= link_to 'Show', adm %></td>
        <td><%= link_to 'Edit', edit_adm_path(adm) %></td>
        <td><%= link_to 'Destroy', adm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adm', new_adm_path %>

app/views/adms/new.html.erb
<h1>New Adm</h1>

<%= render 'form', adm: @adm %>

<%= link_to 'Back', adms_path %>

app/views/adms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @adm.user %>
</p>

<%= link_to 'Edit', edit_adm_path(@adm) %> |
<%= link_to 'Back', adms_path %>