config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :solicitations
  resources :messages
  resources :participantes
  resources :salas
  #get 'salas/:id/solicitacao' => 'salas#show#solicitacao', as: 'solicitacao'
  #post '/sala/:id/solicitacao' => 'salas#show#solicitacao', as: 'solicitacao'
  resources :salas do
  resources :solicitations
  end
  resources :adms
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "salas#index"
  mount ActionCable.server => '/cable'
end

app/models/solicitation.rb
class Solicitation < ApplicationRecord
  belongs_to :user
  belongs_to :sala

  accepts_nested_attributes_for :sala, :user

  def user_nome
	if self.user.blank?
		"Sem Cadastro"
	else
		self.user.nome
	end
  end
end

app/controllers/solicitations_controller.rb
class SolicitationsController < ApplicationController
  before_action :set_solicitation, only: [:show, :edit, :update, :destroy]

  # GET /solicitations
  # GET /solicitations.json
  def index
    @solicitations = Solicitation.all
  end

  # GET /solicitations/1
  # GET /solicitations/1.json
  def show
  end

  # GET /solicitations/new
  def new
    @sala = Sala.find(params[:sala_id])
    @solicitation = Solicitation.new
  end

  # GET /solicitations/1/edit
  def edit
    #@sala = Sala.find(params[:sala_id])
  end

  # POST /solicitations
  # POST /solicitations.json
  def create
    @salas = Sala.all
    @solicitation = Solicitation.new(solicitation_params)
    #@sala = Sala.find.(params[:sala_id])

    respond_to do |format|
      if @solicitation.save
        format.html { redirect_to @solicitation, notice: 'Solicitation was successfully created.' }
        format.json { render :show, status: :created, location: @solicitation }
      else
        format.html { render :new }
        format.json { render json: @solicitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicitations/1
  # PATCH/PUT /solicitations/1.json
  def update
    respond_to do |format|
      if @solicitation.update(solicitation_params)
        format.html { redirect_to @solicitation, notice: 'Solicitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @solicitation }
      else
        format.html { render :edit }
        format.json { render json: @solicitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitations/1
  # DELETE /solicitations/1.json
  def destroy
    @solicitation.destroy
    respond_to do |format|
      format.html { redirect_to solicitations_url, notice: 'Solicitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitation
      @solicitation = Solicitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitation_params
      params.require(:solicitation).permit(:user_id, :sala_id, :texto, :concluida, salas_attributes: [:id, :nome, :descricao, :ativa, :adm_id, :_destroy])
    end
end

app/helpers/solicitations_helper.rb
module SolicitationsHelper
	
end

app/views/solicitations/_form.html.erb
<%= form_for [@sala , @solicitation] do |form| %>
  <% if solicitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solicitation.errors.count, "error") %> prohibited this solicitation from being saved:</h2>

      <ul>
      <% solicitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :sala_id, value: @sala.id %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto %>
  </div>

  <div class="field">
    <%= form.label :concluida %>
    <%= form.check_box :concluida %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/solicitations/_form_edit.html.erb
<%= form_for [@sala , @solicitation] do |form| %>
  <% if solicitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solicitation.errors.count, "error") %> prohibited this solicitation from being saved:</h2>

      <ul>
      <% solicitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :sala_id %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto %>
  </div>

  <div class="field">
    <%= form.label :concluida %>
    <%= form.check_box :concluida %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/solicitations/edit.html.erb
<h1>Editing Solicitation</h1>

<%= render 'form_edit', solicitation: @solicitation %>

<%= link_to 'Show', @solicitation %> |
<%= link_to 'Back', solicitations_path %>

app/views/solicitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Solicitations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Sala</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solicitations.each do |solicitation| %>
      <tr>
        <td><%= solicitation.user %></td>
        <td><%= solicitation.sala %></td>
        <td><%= solicitation.texto %></td>
        <td><%= link_to 'Show', solicitation %></td>
        <td><%= link_to 'Edit', edit_solicitation_path(solicitation) %></td>
        <td><%= link_to 'Destroy', solicitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solicitation', new_solicitation_path %>

app/views/solicitations/new.html.erb
<h1>New Solicitation</h1>

<%= render 'form', solicitation: @solicitation %>

<%= link_to 'Back', solicitations_path %>

app/views/solicitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @solicitation.user.nome %>
</p>

<p>
  <strong>Sala:</strong>
  <%= @solicitation.sala.nome %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @solicitation.texto %>
</p>

<!--%= link_to 'Editar', edit_solicitation_path(@solicitation) %--> |
<%= link_to 'Voltar', salas_path %>