config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :solicitations
  resources :messages
  resources :participantes
  resources :salas
  #get 'salas/:id/solicitacao' => 'salas#show#solicitacao', as: 'solicitacao'
  #post '/sala/:id/solicitacao' => 'salas#show#solicitacao', as: 'solicitacao'
  resources :salas do
  resources :solicitations
  end
  resources :adms
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "salas#index"
  mount ActionCable.server => '/cable'
end

app/models/sala.rb
class Sala < ApplicationRecord
	has_many :messages, dependent: :destroy
	belongs_to :adm, dependent: :destroy
	has_many :participantes
    has_many :solicitations, dependent: :destroy
	#has_and_belongs_to_many :users
	has_many :users, through: :participantes

	accepts_nested_attributes_for :messages, :solicitations, :adm, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :participantes, reject_if: proc { |attributes| attributes[:user_id].blank? }, allow_destroy: true
	accepts_nested_attributes_for :users
	#validates :adm, presence: true
	#validates :participante, uniqueness: true

	#def setar_sala
    #  @sala = current_user.salas.find(params[:id])
    #end
    def sala_id
    	self.sala_id =  Sala.find(params[:id])   	
    end

    def user_nome
    	if self.sala.blank?
      		"Sem Cadastro"
    	else
      		self.sala.user.nome
    	end
    end

    def solicitation_user_nome
        if self.solicitation.blank?
            "Sem Cadastro"
        else
            self.solicitation.user.nome
        end
    end

end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  #before_action :authenticate_user!
  before_action :authorize_sala, only: [:show, :edit, :update, :destroy] 
  before_action :set_sala, only: [:show, :edit, :update, :solicitacao, :destroy]

  # GET /salas
  # GET /salas.json
  def index
    #authorize Sala
    @salas =  policy_scope(Sala).all
    @messages = Message.order(created_at: :asc)
  end

  # GET /salas/1
  # GET /salas/1.json
  def show
    #@messages = Message.all
    @messages = Message.page(params[:page]).per(10).order(created_at: :asc)
    #@message_user = current_user.id
    #@message_sala = @sala.id
    #@sala = Sala.includes(:messages).find_by(id: params[:id])
    #@message = Message.new
    #@messages = Sala.includes(:messages).find_by(id: params[:sala_id])
    #@messages = Message.page(params[:page]).per(10).order(created_at: :asc)
    @participantes = @sala.participantes.build
    @new_solicitation = @sala.solicitations.build
    @solicitations = Solicitation.all
  end

  def solicitacao

  end

  # GET /salas/new
  def new
    @sala = Sala.new
    #@sala.adm_id = current_user.id
    @sala.build_adm
    #@sala.users.build
    #@participante = @sala.participantes.build
    @user = @sala.users.build
    @solicitation = @sala.solicitations.build
    #@adm = @sala.adms.build
  end

  # GET /salas/1/edit
  def edit
    #@sala.adm_id = current_user.id
    #@solicitation = @sala.solicitations.build
  end

  # POST /salas
  # POST /salas.json
  def create
    #@sala = current_user.salas.build(sala_params)
    @sala = Sala.new(sala_params)
    #@sala.build_adm
    #@adm = Adm.new(adm_params)
    #@adm = Adm.new(params[:adm])
    #@sala.adm_id = current_user.id  # Preenchendo o campo com o id

    respond_to do |format|
      if @sala.save
        format.html { redirect_to @sala, notice: 'Sala was successfully created.' }
        format.json { render :show, status: :created, location: @sala }
      else
        format.html { render :new }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salas/1
  # PATCH/PUT /salas/1.json
  def update
    respond_to do |format|
      if @sala.update(sala_params)
        format.html { redirect_to @sala, notice: 'Sala was successfully updated.' }
        format.json { render :show, status: :ok, location: @sala }
      else
        format.html { render :edit }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salas/1
  # DELETE /salas/1.json
  def destroy
    @sala.destroy
    respond_to do |format|
      format.html { redirect_to salas_url, notice: 'Sala was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sala
      @sala = Sala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sala_params
      params.require(:sala).permit(:nome, :descricao, :ativa, :adm_id, adm_attributes: [:id, :user_id, :_destroy, users_attributes: [:id, :email, :nome, :age]], participantes_attributes: [:id, :user_id, :sala_id, :_destroy], users_attributes: [:id, :email, :nome, :age, :password, :password_confirmation, :current_password], solicitations_attributes: [:id, :user_id, :sala_id, :texto, :_destroy])
    end

    def authorize_sala
      authorize Sala
    end
    #def adm_params
    #  params.require(:adm).permit(:user_id)
    #end
end

app/helpers/salas_helper.rb
module SalasHelper
	def user_name
		if @sala.user_ids.blank?
			"Sem Cadastro"
		else
			@sala.users.find(params[:id])
		end
	end

	def solicitation_user_nome
        if self.solicitation.blank?
            "Sem Cadastro"
        else
            self.solicitation.user.nome
        end
    end

end

app/views/salas/_form.html.erb
<%= form_with(model: sala, local: true) do |form| %>
  <% if sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sala.errors.count, "error") %> prohibited this sala from being saved:</h2>

      <ul>
      <% sala.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <font size="2">
  <div class="form-group">
      <%= form.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-12">
      <%= form.text_field :nome %>
    </div>
  </div>

  <div class="form-group">
      <%= form.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-12">
      <%= form.text_area :descricao %>
    </div>
  </div>

  <div class="form-group">
      <%= form.label :ativa, :class => 'control-label col-lg-2' %>
    <div class="col-lg-12">
      <%= form.check_box :ativa %>
    </div>
  </div>

  <div class="form-group">
      <%= form.fields_for :adm, @sala.adm do |f| %>    
      <%= f.hidden_field :user_id, value: current_user.id %>  
      <% end %>
  </div>
  <div class="form-group">
    <h5 class="control-label col-lg-2">Usuários</h5>
    <div id="participantes">
      <%= form.fields_for :participantes do |participante| %>
        <!-- COMENTÁRIO:
          é uma exigencia também que os campos do seu nested esteja numa partial "nome_do_seu_nested_no_singular_fields"
          no nosso caso _experience_fields.html.erb
        -->
        <%= render 'participante_fields', f: participante %>
      <% end %>
   
      <!-- COMENTÁRIO:
        O link para adicionar dinamicamente os fields deve estar dentro de uma div .links
      -->
      <div class="links">
        <!-- COMENTÁRIO: O link_to_add_association é um helper provido pela gem -->
        <%= link_to_add_association 'add usuário', form, :participantes, :class => 'control-label col-lg-12' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= form.submit %>
    </div>
  </div>
<% end %>
  </font>

app/views/salas/_participante_fields.html.erb
<!-- COMENTÁRIO:
  Dentro da partial todo conteúdo deve estar dentro de uma div .nested-fields
-->
<div class="nested-fields">
  <div class="field">
    <div class="col-lg-12">
      <%= f.collection_select :user_id, User.order(:nome), :id, :nome, prompt: 'Selecione' %>
    </div>
  </div>
  <!-- COMENTÁRIO:
    link_to_remove_association é o helper que o cocoon nos fornece para deletar algum nested
  -->
  <%= link_to_remove_association "remove usuário", f, :class => 'control-label col-lg-2' %>
 
  <br><br><br>
</div>

app/views/salas/_solicitacao.html.erb
<%= sala.id %>
<%= render @solicitation %>

app/views/salas/_user_fields.html.erb
<!-- COMENTÁRIO:
  Dentro da partial todo conteúdo deve estar dentro de uma div .nested-fields
-->
<div class="nested-fields">
  <div class="field">
    <%= f.label :nome %>
    <%= f.collection_select :nome, User.order(:nome), :id, :nome, prompt: 'Selecione' %>
  </div>
  <div class="field">
    <!--%= f.label :email %-->
    <!--%= f.email_field :email, autofocus: true %-->
  </div>
  <!-- COMENTÁRIO:
    link_to_remove_association é o helper que o cocoon nos fornece para deletar algum nested
  -->
  <%= link_to_remove_association "remove usuário", f %>
 
  <br><br><br>
</div>

app/views/salas/edit.html.erb
<% @usuario = current_user.id  %>
<% if @usuario == @sala.adm.user.id %>
<div align="center"><h1>Editar Sala</h1></div>

<%= render 'form', sala: @sala %>

<div class="col-lg-offset-2 col-lg-10" align="center">
<%= link_to 'Entrar', @sala, :class => 'btn btn-outline-primary btn-sm' %> |
<%= link_to 'Voltar', salas_path, :class => 'btn btn-primary btn-sm' %>
</div>

<% else %>
<div align="center">
	Você não tem permissão para essa ação!
</br></br>
<div class="col-lg-offset-2 col-lg-10">
	<strong><%= link_to 'Voltar', salas_path, :class => 'btn btn-primary btn-sm' %></strong>
</div>
<% end %>
</div>

app/views/salas/index.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
<h1>Salas de Bate Papo</h1>
</div>
<% if user_signed_in? %>
<div align="center">
<table class="table table-striped" >
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Ativa</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salas.each do |sala| %>
      <tr>
        <td><%= sala.nome %></td>
        <td><%= sala.descricao %></td>
        <td><%= formatar_boolean(sala.ativa) %></td>
        <td><%= sala.adm.user.nome %></td>
        <td><%= link_to 'Entrar', sala, :class => 'btn btn-outline-primary btn-sm' %>
        <%= link_to 'Editar', edit_sala_path(sala), :class => 'btn btn-outline-primary btn-sm' %>
        <% if current_user.id == sala.adm.user.id %>
        <%= link_to 'Deletar', sala, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => 'btn btn-outline-primary btn-sm' %>
        <% else %>
         ::Deletar:: </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<strong><%= link_to 'Nova Sala', new_sala_path, :class => 'btn btn-primary btn-sm' %></strong>
</div>

<% else %>

<div align="center">
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Ativa</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salas.each do |sala| %>
      <tr>
        <td><%= sala.nome %></td>
        <td><%= sala.descricao %></td>
        <td><%= formatar_boolean(sala.ativa) %></td>
        <td><%= sala.adm.user.nome %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% end %>
</div>

app/views/salas/new.html.erb
<div align="center">
	<h1>Nova Sala</h1>
</div>
	<%= render 'form', sala: @sala %>

<div class="col-lg-offset-2 col-lg-10">
	<%= link_to 'Voltar', salas_path, :class => 'btn btn-outline-primary btn-sm' %>
</div>

app/views/salas/show.html.erb
<% @usuario = current_user.id %><br>
<% if ((@sala.adm.user.id == current_user.id) && @sala.users.include?(current_user)) == true %>

<div align="center" class="container">
  <h1 class="title">Bate Papo: Sala <%= @sala.nome %></h1>
  <div id="messages" >
    <!--%= render (@messages).where(sala_id: Sala.find(params[:id])) %-->
    <%= render @sala.messages %>
  </div>
 
  <form>
    <input type="text" data-behavior="sala_speaker" placeholder=" Digite a mensagem aqui: " />
  </form>
  <%= paginate @messages %>
  <br><br>

  <%= link_to 'Voltar', salas_path, :class => 'btn btn-primary btn-sm' %>

</div>
<div align="center" >
  <h3> Participantes: </h3>
  <div id="users"> 
    <% @sala.users.each do |user| %>
    <%= "Nome: #{user.nome}" %>
  </div>
</div>
<% end %>

<div align="center">
 <h3> Solicitações: </h3>
 <% @sala.solicitations.where(concluida: false).each do |solicitation| %>
 <table>
  <thead>
    <tr>
      <th>Usuário</th>
      <th>Sala</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= solicitation.user_nome %></td>
      <td><%= solicitation.sala.nome %></td>
      <td><%= solicitation.texto %></td>
      <td><%= link_to 'Editar', edit_solicitation_path(solicitation) %></td>
    </tr>
    </tbody>
 </table>
  <% end %>
</div>

<% elsif @sala.users.include?(current_user) == true %>
<div align="center" class="container">
  <h1 class="title">Bate Papo: Sala <%= @sala.nome %></h1>
  <div id="messages" >
    <!--%= render (@messages).where(sala_id: Sala.find(params[:id])) %-->
    <%= render @sala.messages %>
  </div>
 
  <form>
    <input type="text" data-behavior="sala_speaker" placeholder=" Digite a mensagem aqui: " />
  </form>
  <%= paginate @messages %>
  <br><br>

  <%= link_to 'Voltar', salas_path, :class => 'btn btn-primary btn-sm' %>

</div>
<div align="right" >
  <h2> Participantes: </h2>
  <div id="users"> 
    <% @sala.users.each do |user| %>
    <%= "Nome: #{user.nome}" %>
  </div>
    <% end %>
</div>

  <% else %>
<div align="center">
  <strong>Não autorizado</strong>
<br/><br/>

  <strong><%= link_to 'Voltar', salas_path, :class => 'btn btn-primary btn-sm' %></strong> </br></br></br>

  <%= link_to 'Solicitação', new_sala_solicitation_path(@sala, @solicitation), :class => 'btn btn-primary btn-sm' %>

    <% end %>
</div>

app/views/salas/show_2.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @sala.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @sala.descricao %>
</p>

<p>
  <strong>Ativa:</strong>
  <%= @sala.ativa %>
</p>

<%= link_to 'Edit', edit_sala_path(@sala) %> |
<%= link_to 'Back', salas_path %>